# Generated by Django 3.2.7 on 2021-09-30 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='نام کافی شاپ')),
                ('description', models.CharField(max_length=1024, verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='نامک')),
                ('address', models.CharField(max_length=512, verbose_name='نشانی')),
                ('owner', models.OneToOneField(limit_choices_to=models.Q(('groups__name', 'Manager')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر کافی شاپ')),
            ],
            options={
                'verbose_name_plural': 'ماژول کافی شاپ ها',
            },
        ),
    ]
