# Generated by Django 3.2.7 on 2021-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(default=1, upload_to='cafes/%Y/%M/%D'),
            preserve_default=False,
        ),
    ]
