# Generated by Django 3.2.7 on 2021-10-07 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafes', '0002_cafe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='owner',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'cafe manager')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر کافی شاپ'),
        ),
    ]
