# Generated by Django 3.2.7 on 2021-10-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafe_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='ویژگی های کافه')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='نامک ویژگی')),
                ('fa_icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='اسم آیکون فوت آسام')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='tags',
            field=models.ManyToManyField(to='cafes.CafeTag', verbose_name='تگ های کافه'),
        ),
    ]
